from __future__ import absolute_import

import AlbumSearchTests
import AppSearchTests
import ArtistSearchTests
import BookSearchTests
import MovieSearchTests
import OtherSearchTests
import PlaceSearchTests
import SuggestedSearchTests
import TrackSearchTests
import TVSearchTests

