
import AlbumSearchTests
import AppSearchTests
import ArtistSearchTests
import BookSearchTests
import MovieSearchTests
import OtherSearchTests
import PlaceSearchTests
import TrackSearchTests
import TVSearchTests

