from __future__ import absolute_import

import NYMagCrawler
import OpenTableCrawler
import UrbanspoonCrawler
import SFMagCrawler
import ZagatCrawler
import LATimesCrawler
import BostonMagCrawler
import ChicagoMagCrawler
import PhillyMagCrawler
import WashMagCrawler
import SeattleTimesCrawler
import SFGateCrawler
import SFWeeklyCrawler
import TimeOutChiCrawler
import TimeOutLACrawler
import TimeOutLVCrawler
import TimeOutMIACrawler
import TimeOutSFCrawler
import YelpCrawler

