#!/usr/bin/env bash

if [ "$#" -eq 1 ]
then
    node=$1
else
    echo "Description:"
    echo "   runs mongostat on the given db"
    echo ""
    echo "Usage:"
    echo "   $0 node-name"
    exit 1
fi

dns=`./get_dns_by_node_name.py $node`
echo "dns:   $dns"

mongostat --host "$dns"

